# Site settings
title: Ars Mentis LLC
email: james@arsmentis.com
description: "Custom software solutions for clients of any size. All problems have solutions. Let me solve yours."
baseurl: ""
url: ""
twitter_username:
github_username:

# Build settings
markdown: kramdown
permalink: pretty
